baseURL = 'http://bkp.app.br/'
languageCode = 'pt-br'
theme = 'graysx'
title = 'BLK Georreferenciamento'

## Site Settings
assetDir = "assets"
[params]
logo = "assets/logo_nav.svg"
favicon = "assets/favicon.svg"

# Info
address = "Av. Dr. Ademar de Barros, 566"
address2 = "São José dos Campos - SP"
email = "contato@blk.app.br"
phone1 = "Fernando (Operações)"
phoneNumber1 = "5512981856229"
phoneNumberSimplified1 = "(12) 98185-6229"
phone2 = "Pedro (Tecnologia)"
phoneNumber2 = "5512997992306"
phoneNumberSimplified2 = "(12) 99799-2306"

# Socials
linkedin = "https://www.linkedin.com/company/blk-mng"
# facebook = "#"
github = "https://github.com/blk-app"
whatsapp = "https://wa.me/5512997992306"

## Menu Items
[menu]
  [[menu.main]]
  name = "Sobre"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Projetos"
  URL = "#projects"
  weight = 2

  [[menu.main]]
  name = "Contato"
  URL = "#contact"
  weight = 3

  [[menu.main]]
  name = "Login"
  URL = "https://odm.blk.app.br/"
  weight = 4
