baseURL = 'http://bkp.app.br/'
languageCode = 'pt-br'
title = 'BLK Aerolevantamento'

## Site Settings
assetDir = "assets"
googleTag = "G-38GBP0L75Z"
[params]
logo = "assets/logo_nav.svg"
favicon = "assets/favicon.svg"

# Info
address = "Av. Dr. Ademar de Barros, 566"
address2 = "São José dos Campos - SP"
email = "contato@blk.app.br"
phoneNumber = "5512988062737"
phoneNumberSimplified = "(12) 98806-2737"

nameCNPJ = "BLK Gestão Empresarial Ltda"
CNPJ = "37.814.104.0001/40"
IE = "125.279.375-118"
IM = "407478"
businessAddres = "Av. Nove de Julho, 685, Sala 53"
businessAddres2 = "São José dos Campos - SP - 12243-000"
pixCNPJ = "37.814.104.0001/40"

# Socials
linkedin = "https://www.linkedin.com/company/blk-aero"
instagram = "https://www.instagram.com/blk.aero"
github = "https://github.com/blk-app"
whatsapp = "https://wa.me/5512988062737"
youtube = "https://www.youtube.com/@blk-aero"

# Menu Items
[menu]
  [[menu.main]]
  name = "Sobre"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Produtos"
  URL = "#products"
  weight = 2

  [[menu.main]]
  name = "Contato"
  URL = "#contact"
  weight = 3
