baseURL = 'http://bkp.app.br/'
languageCode = 'pt-br'
theme = 'graysx'
title = 'BLK Aerolevantamento'

## Site Settings
assetDir = "assets"
[params]
logo = "assets/logo_nav.svg"
favicon = "assets/favicon.svg"

# Info
address = "Av. Dr. Ademar de Barros, 566"
address2 = "São José dos Campos - SP"
email = "contato@blk.app.br"
phoneNumber = "5512988062737"
phoneNumberSimplified = "(12) 98806-2737"

# Socials
linkedin = "https://www.linkedin.com/company/blk-mng"
instagram = "https://www.instagram.com/blk.aero"
github = "https://github.com/blk-app"
whatsapp = "https://wa.me/5512988062737"

## Menu Items
[menu]
  [[menu.main]]
  name = "Sobre"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Projetos"
  URL = "#projects"
  weight = 2

  [[menu.main]]
  name = "Contato"
  URL = "#contact"
  weight = 3

  [[menu.main]]
  name = "Login"
  URL = "https://hub.blk.app.br/"
  weight = 4

# Show Google Slides
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
