baseURL = 'http://bkp.app.br/'
languageCode = 'pt-br'
theme = 'graysx'
title = 'BLK Georreferenciamento'

## Site Settings
[params]
logo = "assets/img/logo.png"
favicon = "assets/favicon.png"

# Info
address = "Av. Nove de Julho, 685"
address2 = "São José dos Campos-SP"
email = "contato@blk.app.br"
phone = "+55 12 99799-2306"

# Socials
linkedin = "https://www.linkedin.com/company/blk-mng"
# facebook = "#"
github = "https://github.com/blk-app"
whatsapp = "https://wa.me/5512997992306"

## Menu Items
[menu]
  [[menu.main]]
  name = "Sobre"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Projetos"
  URL = "#projects"
  weight = 2

  [[menu.main]]
  name = "Contato"
  URL = "#signup"
  weight = 3
