name: Default issue
description: Create a new task or issue
title: "[Short, Action-Oriented Title]"
body:
  - type: markdown
    id: intro
    attributes:
      value: "Please fill out the following sections to the best of your ability. This will help in quickly understanding and addressing the issue."

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: Choose the type of issue you are reporting.
      options:
        - Feature
        - Bug
        - Improvement
        - Documentation
    validations:
      required: true

  - type: textarea
    id: issue_motivation
    attributes:
      label: Issue/Motivation
      description: Describe the context, motivation, and any specific issues.
      placeholder: "Detail the task and its importance..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Discuss your preferred solution and any constraints.
      placeholder: "Describe the ideal solution, including any limitations..."
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Specify the criteria using the Given/When/Then format.
      placeholder: "Given [context], When [action], Then [expected result]..."
    validations:
      required: false

  - type: textarea
    id: blockers
    attributes:
      label: Blocked By
      description: Identify any blockers—other issues—for this task.
      placeholder: "- Issue ..."
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Provide contact information for follow-up.
      placeholder: "e.g., email@example.com"
    validations:
      required: false
